title: Rui Li (李芮)
position: <b>Assistant Professor (Laoshan Scholar, Distinguished Associate Professor)</b>
affiliation: <b>Qingdao University of Science and Technology,</b><br> <b>No.99 Songling Road, Laoshan District，</b> <br> <b>Qingdao, China</b>
email: <b>rui.li@bjtu.edu.cn</b>
email_link: ruilibjtu94@gmail.com
github_link: https://github.com/lirui94
google_scholar: https://scholar.google.com/citations?user=LzIR0B8AAAAJ&hl=zh-CN&oi=ao
avatar: ./assets/img/avatar.png
favicon: ./assets/img/favicon-li.png
favicon_dark: ./assets/img/favicon-li.png
